const data = [
  {
    title: 'The Batman',
    description:
      'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    release_date: '2022-03-01',
    runtime: 176,
    slug: 'the-batman',
    genre: 'Crime, Mystery, Thriller',
    backdrop_img: '5P8SmMzSNYikXpxil6BYzJ16611.jpg',
    poster_img: '74xTEgt7R36Fpooo50r9T25onhq.jpg',
    type: 'movie',
  },
  {
    title: 'Spider-Man: No Way Home',
    description:
      'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
    release_date: '2021-12-15',
    runtime: 148,
    slug: 'spider-man-no-way-home',
    genre: 'Action, Adventure, Science Fiction',
    backdrop_img: 'iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
    poster_img: '1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    type: 'movie',
  },
  {
    title: 'The Outfit',
    description:
      'Leonard is an English tailor who used to craft suits on London’s world-famous Savile Row. After a personal tragedy, he’s ended up in Chicago, operating a small tailor shop in a rough part of town where he makes beautiful clothes for the only people around who can afford them: a family of vicious gangsters.',
    release_date: '2022-02-25',
    runtime: 105,
    slug: 'the-outfit',
    genre: 'Drama, Thriller, Crime',
    backdrop_img: '2n95p9isIi1LYTscTcGytlI4zYd.jpg',
    poster_img: 'ieOVuwnoFC49m7bekmdQ4AynciS.jpg',
    type: 'movie',
  },
  {
    title: 'Turning Red',
    description:
      'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.',
    release_date: '2022-03-10',
    runtime: 100,
    slug: 'turning-red',
    genre: 'Animation, Family, Comedy, Fantasy',
    backdrop_img: 'fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg',
    poster_img: 'qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg',
    type: 'movie',
  },
  {
    title: 'Uncharted',
    description:
      'A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.',
    release_date: '2022-02-10',
    runtime: 116,
    slug: 'uncharted',
    genre: 'Action, Adventure, Family',
    backdrop_img: 'aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg',
    poster_img: 'sqLowacltbZLoCa4KYye64RvvdQ.jpg',
    type: 'movie',
  },
  {
    title: 'Sonic the Hedgehog 2',
    description:
      'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.',
    release_date: '2022-03-30',
    runtime: 122,
    slug: 'sonic-the-hedgehog-2',
    genre: 'Action, Science Fiction, Comedy, Family',
    backdrop_img: 'egoyMDLqCxzjnSrWOz50uLlJWmD.jpg',
    poster_img: '6DrHO1jr3qVrViUO6s6kFiAGM7.jpg',
    type: 'movie',
  },
  {
    title: 'Yaksha: Ruthless Operations',
    description:
      'Nicknamed after a human-devouring spirit, the ruthless leader of an overseas black ops team takes up a dangerous mission in a city riddled with spies.',
    release_date: '2022-04-08',
    runtime: 125,
    slug: 'yaksha-ruthless-operations',
    genre: 'Action',
    backdrop_img: 'hXTWVJMsI9BkxMLliqL1j0FT55t.jpg',
    poster_img: '7MDgiFOPUCeG74nQsMKJuzTJrtc.jpg',
    type: 'movie',
  },
  {
    title: 'Moonfall',
    description:
      'A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.',
    release_date: '2022-02-03',
    runtime: 130,
    slug: 'moonfall',
    genre: 'Action, Adventure, Science Fiction',
    backdrop_img: 'x747ZvF0CcYYTTpPRCoUrxA2cYy.jpg',
    poster_img: 'odVv1sqVs0KxBXiA8bhIBlPgalx.jpg',
    type: 'movie',
  },
  {
    title: 'All the Old Knives',
    description:
      'When the CIA discovers one of its agents leaked information that cost more than 100 people their lives, veteran operative Henry Pelham is assigned to root out the mole with his former lover and colleague Celia Harrison.',
    release_date: '2022-04-08',
    runtime: 102,
    slug: 'all-the-old-knives',
    genre: 'Thriller, Action',
    backdrop_img: 'xicKILMzPn6XZYCOpWwaxlUzg6S.jpg',
    poster_img: 'g4tMniKxol1TBJrHlAtiDjjlx4Q.jpg',
    type: 'movie',
  },
  {
    title: 'Blacklight',
    description:
      'Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.',
    release_date: '2022-02-10',
    runtime: 104,
    slug: 'blacklight',
    genre: 'Action, Thriller',
    backdrop_img: 'iDeWAGnmloZ5Oz3bocDp4rSbUXd.jpg',
    poster_img: 'bv9dy8mnwftdY2j6gG39gCfSFpV.jpg',
    type: 'movie',
  },
  {
    title: 'Encanto',
    description:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    release_date: '2021-11-24',
    runtime: 102,
    slug: 'encanto',
    genre: 'Animation, Comedy, Family, Fantasy',
    backdrop_img: '3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg',
    poster_img: '4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg',
    type: 'movie',
  },
  {
    title: 'War of the Worlds: Annihilation',
    description:
      'A mother and son find themselves faced with a brutal alien invasion where survival will depend on discovering the unthinkable truth about the enemy.',
    release_date: '2021-12-22',
    runtime: 113,
    slug: 'war-of-the-worlds-annihilation',
    genre: 'Science Fiction, Action',
    backdrop_img: 'dqWiut9F30jkiKHHkYTf2RIy1g7.jpg',
    poster_img: '9eiUNsUAw2iwVyMeXNNiNQQad4E.jpg',
    type: 'movie',
  },
  {
    title: 'The Adam Project',
    description:
      'After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.',
    release_date: '2022-03-11',
    runtime: 106,
    slug: 'the-adam-project',
    genre: 'Action, Adventure, Comedy, Science Fiction',
    backdrop_img: 'ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg',
    poster_img: 'wFjboE0aFZNbVOF05fzrka9Fqyx.jpg',
    type: 'movie',
  },
  {
    title: 'No Exit',
    description:
      'Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.',
    release_date: '2022-02-25',
    runtime: 96,
    slug: 'no-exit',
    genre: 'Horror, Thriller',
    backdrop_img: '33wnBK5NxvuKQv0Cxo3wMv0eR7F.jpg',
    poster_img: '5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg',
    type: 'movie',
  },
  {
    title: "Pil's Adventures",
    description:
      "Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks she's a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.",
    release_date: '2021-08-11',
    runtime: 89,
    slug: "pil's-adventures",
    genre: 'Adventure, Animation, Comedy, Family, Fantasy',
    backdrop_img: 'tq3klWQevRK0Or0cGhsw0h3FDWQ.jpg',
    poster_img: 'abPQVYyNfVuGoFUfGVhlNecu0QG.jpg',
    type: 'movie',
  },
  {
    title: 'Gold',
    description:
      'In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.',
    release_date: '2022-01-13',
    runtime: 97,
    slug: 'gold',
    genre: 'Thriller, Action',
    backdrop_img: 'yzH5zvuEzzsHLZnn0jwYoPf0CMT.jpg',
    poster_img: 'ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg',
    type: 'movie',
  },
  {
    title: 'Hotel Transylvania: Transformania',
    description:
      'When Van Helsing\'s mysterious invention, the "Monsterfication Ray," goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it\'s too late, and before they drive each other crazy.',
    release_date: '2022-02-25',
    runtime: 87,
    slug: 'hotel-transylvania-transformania',
    genre: 'Animation, Family, Fantasy, Comedy, Adventure',
    backdrop_img: 'qBLEWvJNVsehJkEJqIigPsWyBse.jpg',
    poster_img: 'teCy1egGQa0y8ULJvlrDHQKnxBL.jpg',
    type: 'movie',
  },
  {
    title: 'Black Crab',
    description:
      'To end an apocalyptic war and save her daughter, a reluctant soldier embarks on a desperate mission to cross a frozen sea carrying a top-secret cargo.',
    release_date: '2022-03-18',
    runtime: 109,
    slug: 'black-crab',
    genre: 'Action, Thriller',
    backdrop_img: 't7I942V5U1Ggn6OevN75u3sNYH9.jpg',
    poster_img: 'mcIYHZYwUbvhvUt8Lb5nENJ7AlX.jpg',
    type: 'movie',
  },
  {
    title: 'Restless',
    description:
      "After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness.",
    release_date: '2022-02-25',
    runtime: 95,
    slug: 'restless',
    genre: 'Action, Thriller, Crime',
    backdrop_img: '7CamWBejQ9JQOO5vAghZfrFpMXY.jpg',
    poster_img: '9MP21x0OPv0R72obd63tMHssmGt.jpg',
    type: 'movie',
  },
  {
    title: 'The In Between',
    description:
      "After surviving a car accident that took the life of her boyfriend, a teenage girl believes he's attempting to reconnect with her from the after world.",
    release_date: '2022-02-11',
    runtime: 116,
    slug: 'the-in-between',
    genre: 'Romance, Science Fiction, Drama',
    backdrop_img: 'i9rEpTqC6aIQOWOc4PDEEAE3hFe.jpg',
    poster_img: '7RcyjraM1cB1Uxy2W9ZWrab4KCw.jpg',
    type: 'movie',
  },
  {
    title: 'Venom: Let There Be Carnage',
    description:
      'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
    release_date: '2021-09-30',
    runtime: 97,
    slug: 'venom-let-there-be-carnage',
    genre: 'Science Fiction, Action, Adventure',
    backdrop_img: 'vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg',
    poster_img: 'rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
    type: 'movie',
  },
  {
    title: 'The Grandmother',
    description:
      'A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.',
    release_date: '2022-01-28',
    runtime: 100,
    slug: 'the-grandmother',
    genre: 'Horror',
    backdrop_img: 'An1nKjXahrChfEbZ3MAE8fsiut1.jpg',
    poster_img: 'eIUixNvox4U4foL5Z9KbN9HXYSM.jpg',
    type: 'movie',
  },
  {
    title: "My Hero Academia: World Heroes' Mission",
    description:
      'A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.',
    release_date: '2021-08-06',
    runtime: 105,
    slug: "my-hero-academia-world-heroes'-mission",
    genre: 'Animation, Action, Fantasy, Adventure',
    backdrop_img: 'cugmVwK0N4aAcLibelKN5jWDXSx.jpg',
    poster_img: '4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg',
    type: 'movie',
  },
  {
    title: 'Eternals',
    description:
      'The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.',
    release_date: '2021-11-03',
    runtime: 156,
    slug: 'eternals',
    genre: 'Science Fiction, Action',
    backdrop_img: 'c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg',
    poster_img: 'bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg',
    type: 'movie',
  },
  {
    title: 'The Ice Age Adventures of Buck Wild',
    description:
      "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
    release_date: '2022-01-28',
    runtime: 82,
    slug: 'the-ice-age-adventures-of-buck-wild',
    genre: 'Animation, Comedy, Adventure, Family',
    backdrop_img: 'eG0oOQVsniPAuecPzDD1B1gnYWy.jpg',
    poster_img: 'zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg',
    type: 'movie',
  },
  {
    title: 'Fantastic Beasts: The Secrets of Dumbledore',
    description:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    release_date: '2022-04-06',
    runtime: 142,
    slug: 'fantastic-beasts-the-secrets-of-dumbledore',
    genre: 'Fantasy, Adventure',
    backdrop_img: 'wdjdHBDwmynWUrJcNzS24uegvK5.jpg',
    poster_img: '8ZbybiGYe8XM4WGmGlhF0ec5R7u.jpg',
    type: 'movie',
  },
  {
    title: 'Bull Shark',
    description:
      'A hungry shark begins feeding on unsuspecting lake goers in a small Texas town.',
    release_date: '2022-02-05',
    runtime: 80,
    slug: 'bull-shark',
    genre: 'Horror',
    backdrop_img: 'u5lEdCvKLkm1EhfQt3qe8Rr5DvR.jpg',
    poster_img: 'wGE4ImqYjJZQi3xFu4I2OLm8m0w.jpg',
    type: 'movie',
  },
  {
    title: 'Sing 2',
    description:
      'Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.',
    release_date: '2021-12-01',
    runtime: 110,
    slug: 'sing-2',
    genre: 'Animation, Comedy, Family, Music',
    backdrop_img: '6mJrgL7Mi13XjJeGYJFlD6UEVQw.jpg',
    poster_img: 'aWeKITRFbbwY8txG5uCj4rMCfSP.jpg',
    type: 'movie',
  },
  {
    title: 'Desperate Riders',
    description:
      'After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, who’s just kidnapped Billy’s mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?',
    release_date: '2022-02-25',
    runtime: 90,
    slug: 'desperate-riders',
    genre: 'Western, Action',
    backdrop_img: 'i5dUmY2xRzgkmjHJYKNj8kPX1Xx.jpg',
    poster_img: '7pYYGm1dWZGkbJuhcuaHD6nE6k7.jpg',
    type: 'movie',
  },
  {
    title: 'The Commando',
    description:
      'An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.',
    release_date: '2022-01-07',
    runtime: 93,
    slug: 'the-commando',
    genre: 'Action, Crime, Thriller',
    backdrop_img: 'pnZ9NMxRqbcJ2dPNROIoregruv5.jpg',
    poster_img: 'mC66fsuzlYHSoZwb6y6emSCaRv5.jpg',
    type: 'movie',
  },
  {
    title: 'Metal Lords',
    description:
      'For teenage misfits Hunter and Kevin, the path to glory is clear: Devote themselves to metal. Win Battle of the Bands. And be worshipped like gods.',
    release_date: '2022-04-08',
    runtime: 97,
    slug: 'metal-lords',
    genre: 'Comedy, Drama, Music',
    backdrop_img: 'gc3QFVNWeTCk2J7XuDIPPoGUWNx.jpg',
    poster_img: 'r97txZRmBb75SGsIAWqmplWJnO3.jpg',
    type: 'movie',
  },
  {
    title: 'Sonic the Hedgehog',
    description:
      'Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.',
    release_date: '2020-02-12',
    runtime: 99,
    slug: 'sonic-the-hedgehog',
    genre: 'Action, Science Fiction, Comedy, Family',
    backdrop_img: 'gnWFYFTTUC62NHSGcMuo4JGK0t4.jpg',
    poster_img: 'aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
    type: 'movie',
  },
  {
    title: 'Fistful of Vengeance',
    description:
      'A revenge mission becomes a fight to save the world from an ancient threat when superpowered assassin Kai tracks a killer to Bangkok.',
    release_date: '2022-02-17',
    runtime: 94,
    slug: 'fistful-of-vengeance',
    genre: 'Action, Crime, Fantasy',
    backdrop_img: 'wMUPT99gw6IB9OVvC46rF8wHIRt.jpg',
    poster_img: '3cccEF9QZgV9bLWyupJO41HSrOV.jpg',
    type: 'movie',
  },
  {
    title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
    description:
      "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
    release_date: '2020-10-16',
    runtime: 117,
    slug: 'demon-slayer--kimetsu-no-yaiba--the-movie-mugen-train',
    genre: 'Animation, Action, Adventure, Fantasy',
    backdrop_img: 'qjGrUmKW78MCFG8PTLDBp67S27p.jpg',
    poster_img: 'h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
    type: 'movie',
  },
  {
    title: "The King's Man",
    description:
      "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
    release_date: '2021-12-22',
    runtime: 131,
    slug: "the-king's-man",
    genre: 'Action, Adventure, Thriller, War, Mystery',
    backdrop_img: '1QW1QHeeW3rZXl6FNKSuqb1kcl8.jpg',
    poster_img: 'aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg',
    type: 'movie',
  },
  {
    title: 'Last Man Down',
    description:
      "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
    release_date: '2021-10-19',
    runtime: 87,
    slug: 'last-man-down',
    genre: 'Action, Thriller',
    backdrop_img: 't4To8feUSysyBs4tlBAbXIrKlCv.jpg',
    poster_img: '4B7liCxNCZIZGONmAMkCnxVlZQV.jpg',
    type: 'movie',
  },
  {
    title: 'The Requin',
    description:
      'A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.',
    release_date: '2022-01-28',
    runtime: 89,
    slug: 'the-requin',
    genre: 'Thriller',
    backdrop_img: 'eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg',
    poster_img: 'i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg',
    type: 'movie',
  },
  {
    title: 'Kimi',
    description:
      'A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.',
    release_date: '2022-02-10',
    runtime: 89,
    slug: 'kimi',
    genre: 'Thriller',
    backdrop_img: 'mruT954ve6P1zquaRs6XG0hA5k9.jpg',
    poster_img: 'okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg',
    type: 'movie',
  },
  {
    title: 'Ghostbusters: Afterlife',
    description:
      'When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.',
    release_date: '2021-11-11',
    runtime: 124,
    slug: 'ghostbusters-afterlife',
    genre: 'Fantasy, Comedy, Adventure',
    backdrop_img: 'zplzc6jxO3SK7Pa4yxVoRY5VflT.jpg',
    poster_img: 'sg4xJaufDiQl7caFEskBtQXfD4x.jpg',
    type: 'movie',
  },
  {
    title: "Pirates of the Caribbean: Dead Man's Chest",
    description:
      'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davy Jones to avoid eternal damnation.',
    release_date: '2006-07-06',
    runtime: 151,
    slug: "pirates-of-the-caribbean-dead-man's-chest",
    genre: 'Adventure, Fantasy, Action',
    backdrop_img: 'vv5a8u6e40kyH0Hp6HuamAgzRai.jpg',
    poster_img: 'uXEqmloGyP7UXAiphJUu2v2pcuE.jpg',
    type: 'movie',
  },
  {
    title: 'Moon Knight',
    description:
      'When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.',
    release_date: '2022-03-30',
    runtime: 1,
    slug: 'moon-knight',
    genre: 'Action & Adventure, Sci-Fi & Fantasy, Mystery',
    backdrop_img: '1uegR4uAxRxiMyX4nQnpzbXhrTw.jpg',
    poster_img: 'zQSABH2Dza4mXLow2f0V2IQvJOL.jpg',
    type: 'series',
  },
  {
    title: 'Halo',
    description:
      'Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.',
    release_date: '2022-03-24',
    runtime: 1,
    slug: 'halo',
    genre: 'Action & Adventure, Sci-Fi & Fantasy',
    backdrop_img: '1qpUk27LVI9UoTS7S0EixUBj5aR.jpg',
    poster_img: 'nJUHX3XL1jMkk8honUZnUmudFb9.jpg',
    type: 'series',
  },
  {
    title: 'Pasión de gavilanes',
    description:
      "The Reyes-Elizondo's idyllic lives are shattered by a murder charge against Eric and León.",
    release_date: '2003-10-21',
    runtime: 2,
    slug: 'pasión-de-gavilanes',
    genre: 'Drama',
    backdrop_img: '4g5gK5eGWZg8swIZl6eX2AoJp8S.jpg',
    poster_img: 'lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg',
    type: 'series',
  },
  {
    title: 'Robinson',
    description:
      'Expedition Robinson is a Swedish reality television program in which contestants are put into survival situations, and a voting process eliminates one person each episode until a winner is determined. The format was developed in 1994 by Charlie Parsons for a United Kingdom TV production company called Planet 24, but the Swedish debut in 1997 was the first production to actually make it to television.',
    release_date: '1997-09-13',
    runtime: 21,
    slug: 'robinson',
    genre: 'Reality',
    backdrop_img: '9hp4JNejY6Ctg9i9ItkM9rd6GE7.jpg',
    poster_img: 'sWA0Uo9hkiAtvtjnPvaqfnulIIE.jpg',
    type: 'series',
  },
  {
    title: 'El Kabeer',
    description:
      "The mayor of Al-Mazareeta, earlier in his life, he met an American woman and had twins with her. One child stayed in Egypt while the other went to America . Once he is on his deathbed, his child that grew up in America goes over to Egypt to claim his father's title. The sons battle to see who will take over, but eventually they realize the value of family, and go through challenges together",
    release_date: '2010-08-11',
    runtime: 6,
    slug: 'el-kabeer',
    genre: 'Comedy',
    backdrop_img: '5dJccl3yF1Er6HVZDceYZC3rzhh.jpg',
    poster_img: 'oj4XM6wpGRIcx3QoQx1PF1fx5E5.jpg',
    type: 'series',
  },
  {
    title: 'Al Asouf',
    description:
      'In the wake of the significant societal changes in the 1970s, the life of a Saudi family is turned upside down after sheltering a baby found at the mosque.',
    release_date: '2018-05-17',
    runtime: 3,
    slug: 'al-asouf',
    genre: 'Drama',
    backdrop_img: 'rjqm1SpsgNGTJutxt1GwxH8AX4V.jpg',
    poster_img: 'g6jYXniFdLDmvGY4DyqXZwKtE5G.jpg',
    type: 'series',
  },
  {
    title: 'My Heart Relieved',
    description:
      'A program that gives you the chance to live a social experience with a young man called "Ghaith". Who is roaming countries to meet people in distress and pain; to look for an opportunity to make a difference in their lives.',
    release_date: '2018-05-17',
    runtime: 5,
    slug: 'my-heart-relieved',
    genre: 'Family, Reality',
    backdrop_img: 'lc2z0xDE6bS90Qo7M3hAJSpW6Df.jpg',
    poster_img: '3iNT3rKs8q7qDr1fWxfznimZ7JV.jpg',
    type: 'series',
  },
  {
    title: 'The Choice',
    description:
      'The story of Ahmed Saber Al-Mansi, commander of the 103rd Brigade, Thunderbolt, who was martyred in the ambush of the Burth Square in the Egyptian city of Rafah in 2017 while responding to a terrorist attack in the Sinai.',
    release_date: '2020-04-24',
    runtime: 3,
    slug: 'the-choice',
    genre: 'Drama, War & Politics, Action & Adventure',
    backdrop_img: 'xJwRWUsATroJvuJXiaMJ038Zf8l.jpg',
    poster_img: 'Rk6iy12bLVIemCcWxPLKH2Cmzz.jpg',
    type: 'series',
  },
  {
    title: 'Till Death',
    description:
      'Fed up with his wife’s distancing from him, Hadi goes on a business trip to Turkey where he meets a special woman, an encounter that changes his life forever.',
    release_date: '2021-04-13',
    runtime: 2,
    slug: 'till-death',
    genre: 'Drama',
    backdrop_img: '4I2H2c6pR7Ws4I8SBAMh6PkdkKz.jpg',
    poster_img: 'g18jnJuhIujMYErHqeG5t8U5F9X.jpg',
    type: 'series',
  },
  {
    title: 'Mohamed Ali Road',
    description:
      'Written secrets are what connects the beaches in Kuwait and Mohamed Ali Road in Mumbai, as a beautiful friendship bonds Shehab and the merchant Abdel Wahab, but the friendship is tarnished when Abdel Wahab betrays his best friend.',
    release_date: '2020-04-24',
    runtime: 2,
    slug: 'mohamed-ali-road',
    genre: 'Drama',
    backdrop_img: '8EqZ8uNx5fEsm5XcciDrDXWBp33.jpg',
    poster_img: 'c4ig0VYwCAnyULaoY4r45ki29h0.jpg',
    type: 'series',
  },
  {
    title: 'Al Maddah',
    description:
      'Saber Al Maddah is a devout and lovable man. Al-Shaytan was able to get him because of the one whose heart was attached to her love, so he killed the closest people to her, and his life was turned upside down.',
    release_date: '2021-04-13',
    runtime: 2,
    slug: 'al-maddah',
    genre: 'Drama',
    backdrop_img: 'opOh9JinJjd6KMF4AdgnDGjWzds.jpg',
    poster_img: 'djvJ6XsHrtMsUwnYn12QAWKfjOh.jpg',
    type: 'series',
  },
  {
    title: 'Just Amina',
    description:
      'A decision to spend her husband’s secret stash of money takes Amina, who leads a simple life, to places she never imagined she would go.',
    release_date: '2021-04-12',
    runtime: 2,
    slug: 'just-amina',
    genre: 'Drama',
    backdrop_img: 'strfWCyNBUzsKjsY9iYOsTJAFgy.jpg',
    poster_img: 'RVgyEIjf1MLREYJIJxvm7O2hF1.jpg',
    type: 'series',
  },
  {
    title: 'Date with Destiny',
    description:
      "We don't have an overview translated in English. Help us expand our database by adding one.",
    release_date: '2022-04-02',
    runtime: 1,
    slug: 'date-with-destiny',
    genre: 'Comedy, Drama',
    backdrop_img: 'fFFRwoykHlk87WdFoU0EzlBAkLk.jpg',
    poster_img: '2XrZwNhWCNqtduTsyEc9xOpEaRy.jpg',
    type: 'series',
  },
  {
    title: 'Ramez Movie Star',
    description:
      'Ramez and co-host Jean-Claude Van Damme trick the stars into thinking they’ll shoot an action-packed movie/ad with the superstar before the actual stunt begins.',
    release_date: '2022-04-02',
    runtime: 1,
    slug: 'ramez-movie-star',
    genre: 'Comedy',
    backdrop_img: 'd5rjvv6J2VGgbNlSU2K7cmo8NhX.jpg',
    poster_img: 'jkwv8b1lJKtpdmt0yf3G3e3i0Nu.jpg',
    type: 'series',
  },
  {
    title: 'Peaky Blinders',
    description:
      'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
    release_date: '2013-09-12',
    runtime: 6,
    slug: 'peaky-blinders',
    genre: 'Drama, Crime',
    backdrop_img: 'wiE9doxiLwq3WCGamDIOb2PqBqc.jpg',
    poster_img: 'vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
    type: 'series',
  },
  {
    title: 'Hollyoaks',
    description:
      'The daily soap that follows the loves, lives and misdemeanours of a group of people living in the Chester village of Hollyoaks where anything could, and frequently does, happen...',
    release_date: '1995-10-23',
    runtime: 28,
    slug: 'hollyoaks',
    genre: 'Soap',
    backdrop_img: 'r8CGqB8IJNbA1IruHWquS7YttNB.jpg',
    poster_img: 'bpmLMZP3M1vLujPqHnOTnKVjRJY.jpg',
    type: 'series',
  },
  {
    title: 'Al Asouf',
    description:
      'In the wake of the significant societal changes in the 1970s, the life of a Saudi family is turned upside down after sheltering a baby found at the mosque.',
    release_date: '2018-05-17',
    runtime: 3,
    slug: 'al-asouf',
    genre: 'Drama',
    backdrop_img: 'rjqm1SpsgNGTJutxt1GwxH8AX4V.jpg',
    poster_img: 'g6jYXniFdLDmvGY4DyqXZwKtE5G.jpg',
    type: 'series',
  },
  {
    title: "The People's Court",
    description:
      "The People's Court is an American arbitration-based reality court show currently presided over by retired Florida State Circuit Court Judge Marilyn Milian. Milian, the show's longest-reigning arbiter, handles small claims disputes in a simulated courtroom set.\n\nThe People's Court is the first court show to use binding arbitration, introducing the format into the genre in 1981. The system has been duplicated by most of the show's successors in the judicial genre. Moreover, The People's Court is the first popular, long-running reality in the judicial genre. It was preceded only by a few short-lived realities in the genre; these short-lived predecessors were only loosely related to judicial proceedings, except for one: Parole took footage from real-life courtrooms holding legal proceedings. Prior to The People's Court, the vast majority of TV courtroom shows used actors, and recreated or fictional cases. Among examples of these types of court shows include Famous Jury Trials and Your Witness.\n\nThe People's Court has had two contrasting lives. The show's first life was presided over solely by former Los Angeles County Superior Court Judge Joseph Wapner. His tenure lasted from the show's debut on September 14, 1981, until May 21, 1993, when the show was cancelled due to low ratings. This left the show with a total of 2,484 ½-hour episodes and 12 seasons. The show was taped in Los Angeles during its first life. After being cancelled, reruns aired until September 9, 1994.",
    release_date: null,
    runtime: 25,
    slug: "the-people's-court",
    genre: 'Reality, Crime',
    poster_img: 'oHGpB5zv3CGar9Xhe1Trrv6uh03.jpg',
    type: 'series',
  },
  {
    title: "Grey's Anatomy",
    description:
      'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
    release_date: '2005-03-27',
    runtime: 18,
    slug: "grey's-anatomy",
    genre: 'Drama',
    backdrop_img: 'dpzC0ACzwkVporKvzZGvNFOBFr6.jpg',
    poster_img: 'zPIug5giU8oug6Xes5K1sTfQJxY.jpg',
    type: 'series',
  },
  {
    title: 'The Walking Dead',
    description:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    release_date: '2010-10-31',
    runtime: 11,
    slug: 'the-walking-dead',
    genre: 'Action & Adventure, Drama, Sci-Fi & Fantasy',
    backdrop_img: 'wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg',
    poster_img: 'xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg',
    type: 'series',
  },
  {
    title: 'The Good Doctor',
    description:
      "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
    release_date: '2017-09-25',
    runtime: 5,
    slug: 'the-good-doctor',
    genre: 'Drama',
    backdrop_img: '6Ys6koNajP5ld9EIMfOSQrRquki.jpg',
    poster_img: 'cXUqtadGsIcZDWUTrfnbDjAy8eN.jpg',
    type: 'series',
  },
];
